import type { McpConfig, McpTool, McpAuthConfig } from '@hatchmcp/shared'

/**
 * Transforms the JSON McpConfig produced by /generate into a complete
 * standalone TypeScript project (the code a user can run on their own
 * machine to host their MCP server). Pure template — no Claude calls.
 *
 * Output layout:
 *   {slug}/
 *     package.json
 *     tsconfig.json
 *     README.md
 *     .env.example
 *     claude_desktop_config.json.example
 *     src/index.ts          (MCP server, stdio transport)
 *     src/tools.ts          (tool definitions + handlers)
 *     src/lib/http.ts       (fetch wrapper with auth injection)
 */
export function generateMcpServerCode(
  config: McpConfig,
  meta: { slug: string }
): Record<string, string> {
  return {
    'package.json': packageJson(meta.slug),
    'tsconfig.json': tsconfig(),
    'README.md': readme(config, meta.slug),
    '.env.example': envExample(config),
    '.gitignore': gitignore(),
    'claude_desktop_config.json.example': claudeConfig(meta.slug, config.server_name),
    'src/index.ts': serverIndex(config),
    'src/tools.ts': toolsModule(config),
    'src/lib/http.ts': httpLib(config.auth_config),
  }
}

/* ──────────────────────── templates ──────────────────────── */

function packageJson(slug: string): string {
  return JSON.stringify(
    {
      name: slug,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: 'MCP server generated by Hatch',
      scripts: {
        build: 'tsc',
        start: 'node dist/index.js',
        dev: 'tsx watch src/index.ts',
      },
      bin: {
        [slug]: './dist/index.js',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^0.6.0',
        axios: '^1.7.0',
        dotenv: '^16.4.0',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        tsx: '^4.7.0',
        typescript: '^5.4.0',
      },
    },
    null,
    2
  ) + '\n'
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        declaration: false,
        sourceMap: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  ) + '\n'
}

function gitignore(): string {
  return ['node_modules/', 'dist/', '.env', '*.log', '.DS_Store', ''].join('\n')
}

function readme(config: McpConfig, slug: string): string {
  const toolBullets = config.tools
    .map((t) => `- \`${t.name}\` — ${t.description}`)
    .join('\n')

  const envVars = envKeys(config)

  return `# ${config.server_name}

> ${config.server_description}

Generated by [Hatch](https://hatch.dev) from your API.

## Setup

\`\`\`bash
npm install
cp .env.example .env       # fill in your credentials
npm run build
\`\`\`

## Connect to Claude Desktop

After \`npm run build\`, the server entry is at \`dist/index.js\`. Add the following
block to your Claude Desktop config (\`~/Library/Application Support/Claude/claude_desktop_config.json\`
on macOS, \`%APPDATA%/Claude/claude_desktop_config.json\` on Windows):

\`\`\`json
{
  "mcpServers": {
    "${slug}": {
      "command": "node",
      "args": ["${'${PWD}'}/dist/index.js"],
      "env": {
${envVars
  .map((k) => `        "${k}": "your-${k.toLowerCase()}-here"`)
  .join(',\n')}
      }
    }
  }
}
\`\`\`

Restart Claude Desktop. The ${config.tools.length} tools below should appear in the tool list.

## Tools

${toolBullets}

## Environment

| Variable | Description |
|---|---|
${envVars.map((k) => `| \`${k}\` | ${envDescription(k, config.auth_config)} |`).join('\n')}

## Notes

- The generated code uses **stdio** transport — Claude Desktop spawns it as a subprocess. To run as an HTTP/SSE server instead, swap \`StdioServerTransport\` in \`src/index.ts\`.
- Tool definitions live in \`src/tools.ts\`. Edit field descriptions, add validators, or remove tools you don't want exposed.
- Auth is injected by \`src/lib/http.ts\`. The auth type is fixed to \`${config.auth_config.type}\` — change it there if your API uses a different scheme.
`
}

function envExample(config: McpConfig): string {
  const lines: string[] = []
  lines.push(`# Base URL of the upstream API`)
  lines.push(`BASE_URL=${config.env.BASE_URL || ''}`)
  lines.push('')

  for (const key of envKeys(config).filter((k) => k !== 'BASE_URL')) {
    lines.push(`${key}=`)
  }
  lines.push('')
  return lines.join('\n')
}

function envKeys(config: McpConfig): string[] {
  const keys = ['BASE_URL']
  // Map each user_must_provide entry to an UPPERCASE env var name
  for (const k of config.auth_config.user_must_provide ?? []) {
    keys.push(envNameFor(k))
  }
  return [...new Set(keys)]
}

function envNameFor(secretKey: string): string {
  // Convert `token`, `api_key`, `username` etc. → `TOKEN`, `API_KEY`, `USERNAME`
  return secretKey.toUpperCase().replace(/[^A-Z0-9]/g, '_')
}

function envDescription(envName: string, auth: McpAuthConfig): string {
  if (envName === 'BASE_URL') return 'Host of the upstream API'
  if (auth.type === 'bearer' && envName === 'TOKEN') return 'Bearer token sent in `Authorization: Bearer <TOKEN>`'
  if (auth.type === 'api_key_header' && envName === 'API_KEY')
    return `API key sent in the \`${auth.header_name ?? 'X-API-Key'}\` header`
  if (auth.type === 'api_key_query' && envName === 'API_KEY')
    return `API key sent as \`?${auth.query_param ?? 'api_key'}=...\``
  if (auth.type === 'basic' && envName === 'USERNAME') return 'HTTP Basic username'
  if (auth.type === 'basic' && envName === 'PASSWORD') return 'HTTP Basic password'
  return 'Secret'
}

function claudeConfig(slug: string, _serverName: string): string {
  return (
    JSON.stringify(
      {
        mcpServers: {
          [slug]: {
            command: 'node',
            args: ['/absolute/path/to/dist/index.js'],
            env: {
              BASE_URL: 'https://api.example.com',
            },
          },
        },
      },
      null,
      2
    ) + '\n'
  )
}

function serverIndex(config: McpConfig): string {
  return `import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js'
import * as dotenv from 'dotenv'
import { TOOLS, HANDLERS } from './tools.js'

dotenv.config()

const server = new Server(
  { name: ${JSON.stringify(config.server_name)}, version: '0.1.0' },
  { capabilities: { tools: {} } },
)

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS,
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const handler = HANDLERS[req.params.name as keyof typeof HANDLERS]
  if (!handler) {
    return {
      content: [{ type: 'text', text: \`Unknown tool: \${req.params.name}\` }],
      isError: true,
    }
  }
  try {
    return await handler((req.params.arguments ?? {}) as Record<string, unknown>)
  } catch (err: unknown) {
    return {
      content: [
        {
          type: 'text',
          text: \`Tool \${req.params.name} threw: \${err instanceof Error ? err.message : String(err)}\`,
        },
      ],
      isError: true,
    }
  }
})

await server.connect(new StdioServerTransport())
console.error(${JSON.stringify(config.server_name)}, 'started over stdio · ${config.tools.length} tools')
`
}

function toolsModule(config: McpConfig): string {
  const defs = config.tools.map(toolDefinition).join(',\n  ')
  const handlers = config.tools.map(toolHandler).join(',\n\n  ')

  return `import { callApi } from './lib/http.js'

export const TOOLS = [
  ${defs},
] as const

export const HANDLERS: Record<string, (args: Record<string, unknown>) => Promise<unknown>> = {
  ${handlers},
}
`
}

function toolDefinition(tool: McpTool): string {
  return `{
    name: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description)},
    inputSchema: ${JSON.stringify(tool.input_schema, null, 4).split('\n').join('\n    ')},
  }`
}

function toolHandler(tool: McpTool): string {
  const urlExpr = renderTemplateAsTs(tool.http.url_template)
  const queryExpr =
    tool.http.query_template != null
      ? renderObjectTemplateAsTs(tool.http.query_template)
      : 'undefined'
  const headersExpr =
    tool.http.headers_template != null
      ? renderObjectTemplateAsTs(tool.http.headers_template)
      : 'undefined'
  const bodyExpr = renderBodyTemplate(tool.http.body_template)
  const successCodes = JSON.stringify(tool.response.success_codes ?? [200])

  return `${tool.name}: async (args) => {
    const url = ${urlExpr}
    const query = ${queryExpr}
    const headers = ${headersExpr}
    const body = ${bodyExpr}
    return callApi({
      method: ${JSON.stringify(tool.http.method)},
      url,
      query,
      headers,
      body,
      successCodes: ${successCodes},
    })
  }`
}

/**
 * Convert a Hatch URL/string template like
 *   "${env.BASE_URL}/v1/users/${args.id}"
 * into a TypeScript expression:
 *   `${process.env.BASE_URL}/v1/users/${String(args.id ?? '')}`
 */
function renderTemplateAsTs(template: string): string {
  const parts: string[] = []
  let cursor = 0
  const re = /\$\{([^}]+)\}/g
  let m: RegExpExecArray | null
  while ((m = re.exec(template))) {
    if (m.index > cursor) parts.push(quoteLiteral(template.slice(cursor, m.index)))
    parts.push(renderSubstitution(m[1].trim()))
    cursor = m.index + m[0].length
  }
  if (cursor < template.length) parts.push(quoteLiteral(template.slice(cursor)))
  if (parts.length === 0) return "''"
  if (parts.length === 1) return parts[0]
  return parts.join(' + ')
}

function renderSubstitution(expr: string): string {
  // env.X       → process.env.X ?? ''
  // args.X      → String(args.X ?? '')
  // auth.token  → process.env.TOKEN ?? ''
  // auth.api_key→ process.env.API_KEY ?? ''
  if (expr.startsWith('env.')) {
    const name = expr.slice(4)
    return `(process.env.${name} ?? '')`
  }
  if (expr.startsWith('args.')) {
    const path = expr.slice(5)
    // args may be nested — args.user.name etc. For the common single-level case
    // we can index safely; deeper paths fall back to safe optional chains.
    if (/^[A-Za-z_][\w]*$/.test(path)) {
      return `String(args.${path} ?? '')`
    }
    const chain = path
      .split('.')
      .map((p) => (/^[A-Za-z_][\w]*$/.test(p) ? `.${p}` : `[${JSON.stringify(p)}]`))
      .join('')
    return `String((args${chain}) ?? '')`
  }
  if (expr.startsWith('auth.')) {
    const key = expr.slice(5)
    return `(process.env.${envNameFor(key)} ?? '')`
  }
  // Unknown namespace — leave as-is but coerce safely
  return `String(${JSON.stringify('${' + expr + '}')})`
}

function renderObjectTemplateAsTs(obj: Record<string, string>): string {
  const entries = Object.entries(obj)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${renderTemplateAsTs(v)}`)
    .join(',\n')
  return `{\n${entries},\n    } as Record<string, string>`
}

function renderBodyTemplate(body: McpTool['http']['body_template'] | undefined): string {
  if (body == null) return 'undefined'
  if (typeof body === 'string') return renderTemplateAsTs(body)
  // Object body
  const entries = Object.entries(body)
    .map(([k, v]) => `    ${JSON.stringify(k)}: ${renderBodyValueAsTs(v)}`)
    .join(',\n')
  return `{\n${entries},\n    }`
}

function renderBodyValueAsTs(v: unknown): string {
  if (typeof v === 'string') return renderTemplateAsTs(v)
  return JSON.stringify(v)
}

function quoteLiteral(s: string): string {
  return JSON.stringify(s)
}

function httpLib(auth: McpAuthConfig): string {
  return `import axios from 'axios'

export interface CallApiArgs {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  url: string
  headers?: Record<string, string> | undefined
  query?: Record<string, string> | undefined
  body?: unknown
  successCodes?: number[]
}

export interface CallApiResult {
  content: { type: 'text'; text: string }[]
  isError?: boolean
}

export async function callApi(args: CallApiArgs): Promise<CallApiResult> {
  const headers: Record<string, string> = { ...(args.headers ?? {}) }

${authInjection(auth)}

  try {
    const res = await axios.request({
      method: args.method,
      url: args.url,
      headers,
      params: args.query,
      data: args.body,
      validateStatus: () => true,
      timeout: 30_000,
    })

    const success = (args.successCodes ?? [200, 201, 204]).includes(res.status)
    if (!success) {
      return {
        content: [
          {
            type: 'text',
            text: \`HTTP \${res.status}: \${typeof res.data === 'string' ? res.data : JSON.stringify(res.data, null, 2)}\`,
          },
        ],
        isError: true,
      }
    }

    return {
      content: [
        {
          type: 'text',
          text: typeof res.data === 'string' ? res.data : JSON.stringify(res.data, null, 2),
        },
      ],
    }
  } catch (err) {
    return {
      content: [
        {
          type: 'text',
          text: \`Network error: \${err instanceof Error ? err.message : String(err)}\`,
        },
      ],
      isError: true,
    }
  }
}
`
}

function authInjection(auth: McpAuthConfig): string {
  switch (auth.type) {
    case 'bearer':
      return `  // Bearer token auth
  const token = process.env.TOKEN
  if (token) headers['Authorization'] = ${JSON.stringify(auth.header_prefix ?? 'Bearer ')} + token`

    case 'api_key_header': {
      const header = auth.header_name ?? 'X-API-Key'
      return `  // API key in header
  const apiKey = process.env.API_KEY
  if (apiKey) headers[${JSON.stringify(header)}] = apiKey`
    }

    case 'api_key_query': {
      const param = auth.query_param ?? 'api_key'
      return `  // API key in query string
  const apiKey = process.env.API_KEY
  if (apiKey) {
    args.query = { ...(args.query ?? {}), ${JSON.stringify(param)}: apiKey }
  }`
    }

    case 'basic':
      return `  // HTTP Basic auth
  const user = process.env.USERNAME
  const pass = process.env.PASSWORD
  if (user && pass) {
    const encoded = Buffer.from(\`\${user}:\${pass}\`).toString('base64')
    headers['Authorization'] = \`Basic \${encoded}\`
  }`

    case 'oauth2_client_credentials':
      return `  // OAuth2 client_credentials — paste a pre-generated access token
  const token = process.env.ACCESS_TOKEN
  if (token) headers['Authorization'] = \`Bearer \${token}\``

    case 'none':
    default:
      return `  // No auth — endpoints are public`
  }
}
